kind: ServiceSpec
apiVersion: hyscale.io/v1/
metadata:
  name: database
  version: 1
  replicas: 1
  resourceLimits:
    memory: 512
  healthChecks:
  - port: 3306
    healthCheckType: TCP
spec:
  stack:
    name: mysql
    version: 5.6
    docker-registry: dockerhublibrary
    importImage: mysql:5.6
    ports:
    - name: mysql-port
      type: TCP
      port: 3306
      default: 3306 # why
    os: Ubuntu:14.04 # To be removed
    distribution: DEBIAN # why
  dataDirectories:
   - name: mysql-data-dir
     path: "/var/lib/mysql"
     readOnly: false
     sizeInGB: "{{ MYSQL_DATA_DIR_IN_GB | default('1')}}"
     storageClass: "{{ STORAGE_CLASS | default('default') }}"
  config:
    props:
    - key: MYSQL_ROOT_PASSWORD
      type: PASSWORD
      value: "{{ MYSQL_ROOT_PASSWORD | default('') }}"
    - key: MYSQL_DATABASE
      value: "dockerApp"
