# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Agent.BuildDirectory)/s'
    includeRootFolder: false
    archiveType: 'tar'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).tar.gz'
    replaceExistingArchive: true
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'hyscalectl-docker-jumpbox'
    sourceFolder: '$(Build.ArtifactStagingDirectory)/'
    contents: '**'
    targetFolder: '/tmp/todo_demo/$(Build.BuildNumber)/todo/'
- task: SSH@0
  inputs:
    sshEndpoint: 'hyscalectl-docker-jumpbox'
    runOptions: 'commands'
    commands: 'tar -xzf /tmp/todo_demo/$(Build.BuildNumber)/todo/$(Build.BuildNumber).tar.gz -C /tmp/todo_demo/$(Build.BuildNumber)/todo/
      
      /usr/bin/docker build --target install -t todo_app_artifact_image:$(Build.BuildNumber) -f /tmp/todo_demo/$(Build.BuildNumber)/todo/app/Dockerfile /tmp/todo_demo/$(Build.BuildNumber)/'



