# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'tar'
    archiveFile: '$(Build.ArtifactStagingDirectory)/dist/$(Build.BuildNumber).tar.gz'
    replaceExistingArchive: true
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'hyscalectl-docker-jumpbox'
    sourceFolder: '$(Build.ArtifactStagingDirectory)/dist'
    contents: '**'
    targetFolder: '/tmp/todo_demo/$(Build.BuildNumber)/todo/'


