# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'hyscalectl-docker-jumpbox'
    contents: '**'
    targetFolder: '/tmp/todo_demo/$(Build.BuildNumber)/todo/' 
- task: SSH@0
  inputs:
    sshEndpoint: 'hyscalectl-docker-jumpbox'
    runOptions: 'commands'
    commands: '/usr/bin/docker build --target install -t todo_app_artifact_image:$(Build.BuildNumber) -f /tmp/todo_demo/$(Build.BuildNumber)/todo/app/Dockerfile /tmp/todo_demo/$(Build.BuildNumber)/'

