version: '2'
services:
    web:
        container_name: todo_list_web
        build:
            context: ./
            dockerfile: ./web/Dockerfile
#        volumes:
#            - ./src:/var/www
        ports:
            - "8888:80"
        links:
            - app
        environment:
            - "APP_HOST=app"
            - "APP_PORT=9000"
    app:
     
        container_name: todo_list_app
        build:
            context: ./
            dockerfile: ./app/Dockerfile
#        volumes:
#            - ./src:/var/www
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
    database:
        container_name: todo_list_mysql
        image: mysql:5.6
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=dockerApp"
        ports:
            - "33061:3306"
        volumes:
            - ./db/dockerApp.sql:/docker-entrypoint-initdb.d/dockerApp.sql
