version: '2'
services:
    web:
        container_name: todo_list_web
        image: vijaysamanuri/todo-web:1.0
        ports:
            - "8888:80"
        links:
            - app
        environment:
            - "APP_HOST=app"
            - "APP_PORT=9000"
    app:
        container_name: todo_list_app
        image: vijaysamanuri/todo-app:1.0
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
    database:
        container_name: todo_list_mysql
        image: mysql:5.6
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=dockerApp"
        ports:
            - "33061:3306"
        volumes:
            - ./db/dockerApp.sql:/docker-entrypoint-initdb.d/dockerApp.sql
