app:
  REPLICAS: 1
  MEMORY_LIMIT_IN_MB: 1024
  BUILD_NUMBER: @@BUILD_NUMBER@@
  DB_PASSWORD:
  APP_ENV: local
  APP_DEBUG: true
  APP_LOG: daily
  APP_LOG_LEVEL: debug
  APP_DEMO: true
  CLI_TEST: dev-v1
web:
  REPLICAS: 1
  MEMORY_LIMIT_IN_MB: 1024
  BUILD_NUMBER: @@BUILD_NUMBER@@
database:
  REPLICAS: 1
  MEMORY_LIMIT_IN_MB: 1024
  BUILD_NUMBER: @@BUILD_NUMBER@@
  MYSQL_ROOT_PASSWORD:
